# Generated by Django 4.1 on 2024-05-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rioz", "0002_alter_information_avatar_alter_information_contact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_bio", models.CharField(max_length=100)),
                ("intro", models.CharField(max_length=350)),
            ],
        ),
        migrations.RemoveField(
            model_name="information",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="information",
            name="intro",
        ),
        migrations.AddField(
            model_name="information",
            name="cover_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/images/cover_pic/"
            ),
        ),
    ]
