# Generated by Django 4.1 on 2024-05-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rioz", "0005_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_info",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_name",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
