# Generated by Django 4.1 on 2024-05-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rioz", "0006_service_service_info_alter_service_service_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="information",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="static/cv/"),
        ),
    ]
