# Generated by Django 4.1 on 2024-05-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rioz", "0007_experience_website_alter_experience_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
