# Generated by Django 5.0.6 on 2024-06-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rioz', '0010_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
