# Generated by Django 5.0.6 on 2024-06-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rioz', '0011_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_topic',
            field=models.CharField(max_length=150),
        ),
    ]
