# Generated by Django 5.0.6 on 2024-06-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rioz', '0012_alter_blog_blog_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_apprroved',
            field=models.BooleanField(default=False),
        ),
    ]
