# Generated by Django 5.0.6 on 2024-06-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rioz', '0013_comments_is_apprroved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='is_apprroved',
            new_name='is_approved',
        ),
    ]
