# Generated by Django 5.0.6 on 2024-06-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rioz', '0015_alter_comments_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_id',
        ),
    ]
